use_frameworks!

platform :ios, '8.0'

target 'EB_BaseNetworkManager_Example' do
  pod 'EB_BaseNetworkManager', :path => '../'

  target 'EB_BaseNetworkManager_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
